// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uauzfpbxrawxfubeqwyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhdXpmcGJ4cmF3eGZ1YmVxd3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4MTc0NTksImV4cCI6MjA1MTM5MzQ1OX0.hf-mBtC5FN0EaozPHZo5GS2GplOR-Nzl0rIoHc0zOQc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);